# Generated by Django 4.2.13 on 2024-07-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_roles_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='questions',
        ),
    ]
