# Generated by Django 4.2.13 on 2024-07-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_title_assignment_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='questions',
            new_name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
