# Generated by Django 4.2.13 on 2024-07-02 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_remove_assignment_user_remove_assignment_pdf_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignmentAnswers',
            new_name='AssignmentAnswer',
        ),
    ]
