# Generated by Django 4.2.13 on 2024-07-02 11:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_assignmentanswers_assignmentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
