# Generated by Django 4.2.13 on 2024-07-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_assignment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='main.chapter'),
        ),
    ]
