# Generated by Django 4.2.13 on 2024-07-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_assignmentanswer_date_assignmentanswer_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='semester',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
    ]
