# Generated by Django 4.2.13 on 2024-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
