# Generated by Django 4.2.13 on 2024-07-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgpa',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgpa', to='main.semester'),
        ),
    ]
